# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Butter blog
email: aartasas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Passion in cycling and coding. Working hard, dreaming big. Doing what is right, not what is easy.
baseurl: "/butter-blog" # the subpath of your site, e.g. /blog
url: "/butter-blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: neonartur
github_username:  neone35
my_name: Artūr Maslov

# Destination inside folder for github pages
destination: _site/butter-blog

# Build settings
markdown: kramdown
highlighter: rouge
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-admin

# Minima config
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize date
minima:
  date_format: "%F"
disqus:
    shortname: butter-blog

# Additional types of documents (e.g post, page)
collections:
  portfolio:
      output: true
      permalink: /:collection/:name

# google_analytics: ""

############################################################
# Site configuration for the Jekyll 3 Pagination Gem (jekyll-paginate-v2)
# The values here represent the defaults if nothing is set
pagination:
  enabled: true
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/blog-pages/:num/'
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
  # Optional, the default tag to use, omit to disable
  tag: ''
 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2
  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html
  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'
############################################################
